# Generated by Django 5.0.6 on 2024-07-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cinemashowtime',
            old_name='cinema',
            new_name='cinema_name',
        ),
    ]
